name: Docker Image Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.2
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
        # go-version: # optional
        # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
        check-latest: true
        # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
        # cache: # optional, default is true
        # Used to specify the path to a dependency file - go.sum
        # cache-dependency-path: # optional
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
